[package]
name = "DoIt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.4.7", features = ["cargo"] }
serde = "1.0.228"
serde_json = "1.0.147"
dotenvy = "0.15.7"

data = { path = "../data" }
domain = { path = "../domain" }
shared = { path = "../shared" }